sudo: required

language: csharp

cache:
    directories:
        - packages

services:
    - docker

before_install:
    - docker build -t webapp:test -f ./dockerfile .

script:
    - docker run -it -v $PWD/packages:/root/.nuget/packages webapp:test